spring:
  application:
    name: cache-api

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/event
    username: postgres
    password: postgres

  jpa:
    open-in-view: false
    properties:
      hibernate:
        type:
          json_format_mapper: jackson