---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gapa-second
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: gapa-second
spec:
  protocol: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gapa-second
    release: v1
  name: gapa-second
spec:
  selector:
    matchLabels:
      service: gapa-second
      app: gapa-second
      release: v1
  replicas: 1
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/service-meta-version: 'v1'
        consul.hashicorp.com/connect-service-upstreams: 'zipkin:9411'
      labels:
        service: gapa-second
        app: gapa-second
        release: v1
    spec:
      serviceAccountName: gapa-second
      containers:
      - name: gapa-second
        image: segware/gapa-second:1.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "400m"
          limits:
            memory: "256Mi"
            cpu: "800m"
        ports:
        - containerPort: 8082
        env:
          - name: NAME
            value: "Second (v1)"
          - name: MESSAGE
            value: "Second (v1)"
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: gapa-second
  labels:
    app: gapa-second
  annotations:
    ingress.kubernetes.io/service-upstream: 'true'
spec:
  selector:
    app: gapa-second
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8082
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: to-second
spec:
  destination:
    name: gapa-second
  sources:
    - name: gapa-service
      action: allow