micronaut:
  application:
    name: micronaut-web

  i18n:
    default-locale: en_GB

  metrics:
    enabled: true

datasources:
  default:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: postgres

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

endpoints:
  prometheus:
    sensitive: false

