apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: order
  labels:
    app: order
spec:
  protocol: http
  rateLimits:
    instanceLevel:
      requestsPerSecond: 5
      requestsMaxBurst: 10
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: order
  labels:
    app: order
spec:
  destination:
    name: order
  sources:
    - name: api-gateway
      action: allow