{
 "title": "APM",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service name",
    "query": {
     "query": "label_values(jvm_thread_count,service_name)"
    }
   },
   {
    "name": "quantile",
    "label": "Quantile",
    "query": "P99 : 0.99,P95 : 0.95,P90 : 0.90,P50 : 0.50"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(http_server_request_duration_seconds_count{service_name=\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kafka_consumer_records_consumed_total{service_name=\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kafka_producer_record_send_total{service_name=\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(db_client_connections_usage{service_name=\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Web", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{service_name=\"$service\"}[$__rate_interval])) by (http_route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_server_request_duration_seconds_count{service_name=\"$service\",http_response_status_code=~\"5..\"}[5m])) by (http_route)\n  or\n  sum(rate(http_server_request_duration_seconds_count{service_name=\"$service\"}[5m])) by (http_route) * 0\n)\n/\nsum(rate(http_server_request_duration_seconds_count{service_name=\"$service\"}[5m])) by (http_route) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum by (le, http_route) (rate(http_server_request_duration_seconds_bucket{service_name=\"$service\"}[$__rate_interval]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_server_request_duration_seconds_bucket{service_name=\"$service\", le=\"0.25\"}[$__rate_interval]))\n  +\n  0.5 * (\n    sum(rate(http_server_request_duration_seconds_bucket{service_name=\"$service\", le=\"1.0\"}[$__rate_interval]))\n    -\n    sum(rate(http_server_request_duration_seconds_bucket{service_name=\"$service\", le=\"0.25\"}[$__rate_interval]))\n  )\n)\n/ ignoring(le)\nsum(rate(http_server_request_duration_seconds_count{service_name=\"$service\"}[$__rate_interval]))\n",
     "legendFormat": "Apdex"
    }
   ]
  },
  {
   "title": "Tracing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({service_name=\"$service\"}       [$__auto])) by (detected_level)",
       "legendFormat": "{{detected_level}}"
      }
     ]
    },
    {
     "type": "logs",
     "gridPos": { "h": 6, "w": 16, "x": 8, "y": 44 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{service_name=\"$service\"} | json | logfmt | drop __error__, __error_details__"
      }
     ]
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Profiler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "type": "flamegraph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 70 },
     "targets": [
      {
       "labelSelector": "{service_name=\"$service\"}",
       "profileTypeId": "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(db_client_connections_use_time_milliseconds_count{service_name=\"$service\"}[5m])",
       "legendFormat": "Throughput"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(db_client_connections_usage{service_name=\"$service\"}) / avg(db_client_connections_max{service_name=\"$service\"})",
       "legendFormat": "Pool usage"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 82 },
     "targets": [
      {
       "expr": "db_client_connections_pending_requests{service_name=\"$service\"}",
       "legendFormat": "Pending requests"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "rec/s" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_producer_record_send_total{service_name=\"$service\"}[$__rate_interval]))",
       "legendFormat": "Producer throughput (rec/s)"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "rec/s" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_consumer_records_consumed_total{service_name=\"$service\"}[$__rate_interval]))",
       "legendFormat": "Consumer throughput (rec/s)"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_producer_byte_total{service_name=\"$service\"}[$__rate_interval])) / 1024 / 1024",
       "legendFormat": "Producer throughput (MB/s)"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_consumer_bytes_consumed_total{service_name=\"$service\"}[$__rate_interval])) / 1024 / 1024",
       "legendFormat": "Consumer throughput (MB/s)"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "avg(kafka_producer_batch_size_avg{service_name=\"$service\"}) / 1024 / 1024",
       "legendFormat": "Producer batch size (avg MB)"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "rec" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_records_lag{service_name=\"$service\"})",
       "legendFormat": "Consumer lag (rec)"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(kafka_producer_request_latency_avg{service_name=\"$service\"})",
       "legendFormat": "Producer latency (avg ms)"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "rec/s" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_consumer_fetch_total{service_name=\"$service\"}[$__rate_interval]))",
       "legendFormat": "Consumer fetch size (rec/s)"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "rec/s" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_producer_record_error_total{service_name=\"$service\"}[$__rate_interval]))",
       "legendFormat": "Producer errors (rec/s)"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(kafka_consumer_time_between_poll_avg{service_name=\"$service\"})",
       "legendFormat": "Consumer time between poll (avg ms)"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "rec/s" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_producer_record_retry_total{service_name=\"$service\"}[$__rate_interval]))",
       "legendFormat": "Producer retries (rec/s)"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "c/s" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_consumer_commit_total{service_name=\"$service\"}[$__rate_interval]))",
       "legendFormat": "Consumer commits (c/s)"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true
  }
 ]
}