services:
  postgres:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - '8081:8080'

  prometheus:
    image: prom/prometheus:v2.52.0
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana:10.1.10
    restart: always
    ports:
      - '3000:3000'