{
 "title": "Vert.x Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vertx_http_server_active_connections",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Request count rate by status code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(vertx_http_server_requests_total[1m])) by (code), 0.001)"
    }
   ]
  },
  {
   "title": "Request count rate by code and route",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(vertx_http_server_requests_total[1m])) by (code,route), 0.001)"
    }
   ]
  },
  {
   "title": "Global response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_http_server_response_time_seconds_sum[1m])) / sum(irate(vertx_http_server_response_time_seconds_count[1m]))",
     "legendFormat": "[avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_response_time_seconds_bucket[1m])) by (le))",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_http_server_response_time_seconds_bucket[1m])) by (le))",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_response_time_seconds_bucket[1m])) by (le))",
     "legendFormat": "[99p]"
    }
   ]
  },
  {
   "title": "Response time by route",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_http_server_response_time_seconds_sum[1m])) by (route) / sum(irate(vertx_http_server_response_time_seconds_count[1m])) by (route)",
     "legendFormat": "{{route}} [avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_response_time_seconds_bucket[1m])) by (le,route))",
     "legendFormat": "{{route}} [med]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_response_time_seconds_bucket[1m])) by (le,route))",
     "legendFormat": "{{route}} [99p]"
    }
   ]
  },
  {
   "title": "Eventbus: handlers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vertx_eventbus_handlers", "legendFormat": "handlers" }
   ]
  },
  {
   "title": "Eventbus: pending",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vertx_eventbus_pending{side=\"local\"}",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Eventbus: sent rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_sent_total[1m]))",
     "legendFormat": "1 minute instant rate"
    },
    {
     "expr": "sum(rate(vertx_eventbus_sent_total[1m]))",
     "legendFormat": "1 minute rate"
    },
    {
     "expr": "sum(rate(vertx_eventbus_sent_total[5m]))",
     "legendFormat": "5 minute rate"
    }
   ]
  },
  {
   "title": "Eventbus: received rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_received_total[1m]))",
     "legendFormat": "1 minute instant rate"
    },
    {
     "expr": "sum(rate(vertx_eventbus_received_total[1m]))",
     "legendFormat": "1 minute rate"
    },
    {
     "expr": "sum(rate(vertx_eventbus_received_total[5m]))",
     "legendFormat": "5 minute rate"
    }
   ]
  }
 ]
}