apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse
  labels:
    app: warehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouse
  template:
    metadata:
      labels:
        app: warehouse
      annotations:
        consul.hashicorp.com/connect-inject: "true"
    spec:
      serviceAccountName: warehouse
      containers:
        - name: warehouse
          image: warehouse
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector-opentelemetry-collector.observability:4318"
          resources:
            requests:
              memory: 1Gi
            limits:
              memory: 1Gi