spring:
  application:
    name: pong

  ssl:
    bundle:
      jks:
        pong-bundle:
          reload-on-update: true
          keystore:
            location: file:pong_keystore.jks
            password: test123
            type: JKS
          truststore:
            location: file:pong_truststore.jks
            password: test123
            type: JKS
server:
  port: 8444
  ssl:
    client-auth: need
    bundle: pong-bundle

