spring:
  application:
    name: pong

  ssl:
    bundle:
      jks:
        pong-bundle:
          reload-on-update: true
          keystore:
            location: classpath:signed-by-intermediate/pong-keystore.jks
            password: test123
            type: JKS
          truststore:
            location: classpath:signed-by-intermediate/pong-truststore.jks
            password: test123
            type: JKS
server:
  port: 8444
  ssl:
    client-auth: need
    bundle: pong-bundle

