---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gapa-crud
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: gapa-crud
spec:
  protocol: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gapa-crud
    release: v1
  name: gapa-crud
spec:
  selector:
    matchLabels:
      service: gapa-crud
      app: gapa-crud
      release: v1
  replicas: 1
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/service-meta-version: 'v1'
        consul.hashicorp.com/connect-service-upstreams: 'zipkin:9411'
      labels:
        service: gapa-crud
        app: gapa-crud
        release: v1
    spec:
      serviceAccountName: gapa-crud
      containers:
      - name: gapa-crud
        image: segware/gapa-crud:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8083
        env:
          - name: NAME
            value: "CRUD (v1)"
          - name: MESSAGE
            value: "CRUD (v1)"
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: gapa-crud
  labels:
    app: gapa-crud
  annotations:
    ingress.kubernetes.io/service-upstream: 'true'
spec:
  selector:
    app: gapa-crud
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8083
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: to-second
spec:
  destination:
    name: gapa-crud
  sources:
    - name: gapa-service
      action: allow