spring:
  application:
    name: ping

  ssl:
    bundle:
      jks:
        ping-bundle:
          reload-on-update: true
          keystore:
            location: file:ping_keystore.jks
            password: test123
            type: JKS
          truststore:
            location: file:ping_truststore.jks
            password: test123
            type: JKS
server:
  port: 8081

pong:
  host: api.segwarez.com
  port: 8444

