spring:
  application:
    name: Spring Web

  web:
    locale: en_GB

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, metrics, prometheus
