server:
  port: 8083

spring:
  application:
    name: gapa-crud
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:8085/auth/realms/Gapa/protocol/openid-connect/token/introspect
          client-id: Gapa
          client-secret: d9d13ee5-f0f7-41aa-8f3b-d362c8682a16

springdoc:
  packages-to-scan: pl.com.segware.gapa.crud.repositories

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, prometheus, metrics