global:
  name: gapa-consul
  datacenter: gapa-datacenter
  gossipEncryption:
    autoGenerate: true
  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true
  acls:
    manageSystemACLs: true
  metrics:
    enabled: true
    agentMetricsRetentionTime: "1m"
    
server:
  replicas: 1
  extraConfig: |
    {
      "ui_config": {
        "dashboard_url_templates": {
          "service": "http://localhost:3000/d/lDlaj-NGz/service-overview?orgId=1&var-service={{ "{{" }}Service.Name}}&var-namespace={{ "{{" }}Service.Namespace}}&var-dc={{ "{{" }}Datacenter}}"
        }
      }
    }

client:
  enabled: true
  grpc: true

ui:
  enabled: true
  service:
    type: LoadBalancer

connectInject:
  enabled: true

controller:
  enabled: true