apiVersion: v1
kind: ServiceAccount
metadata:
  name: zipkin
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: zipkin
spec:
  protocol: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zipkin
  name: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      service: zipkin
      app: zipkin
  template:
    metadata:
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
      labels:
        service: zipkin
        app: zipkin
    spec:
      serviceAccountName: zipkin
      containers:
        - name: zipkin
          image: openzipkin/zipkin
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9411
          env:
            - name: STORAGE_TYPE
              value: mem
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  labels:
    name: zipkin
spec:
  ports:
  - port: 9411
    targetPort: 9411
  selector:
    app: zipkin
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: to-zipkin
spec:
  destination:
    name: zipkin
  sources:
    - name: gapa-service
      action: allow
    - name: gapa-second
      action: allow