apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: billing
  labels:
    app: billing
spec:
  destination:
    name: billing
  sources:
    - name: order
      action: allow