apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing
  labels:
    app: billing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        app: billing
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "warehouse:8081"
    spec:
      serviceAccountName: billing
      containers:
        - name: billing
          image: billing
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8082
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector-opentelemetry-collector.observability:4317"
          resources:
            requests:
              memory: 1Gi
            limits:
              memory: 1Gi