global:
  name: consul
  datacenter: minikube

  tls:
    enabled: true
    enableAutoEncrypt: true

  acls:
    manageSystemACLs: true

  gossipEncryption:
    autoGenerate: true

  metrics:
    enabled: true
    enableAgentMetrics: true

server:
  replicas: 1

client:
  enabled: true

connectInject:
  enabled: true

ui:
  enabled: true
  service:
    type: ClusterIP

  metrics:
    enabled: true
    baseURL: http://prometheus-kube-prometheus-prometheus.observability:9090

  dashboardURLTemplates:
    service: "http://localhost:3000/d/lDlaj-NGz/service-overview?orgId=1&var-service={{Service.Name}}&var-namespace={{Service.Namespace}}&var-dc={{Datacenter}}"