global:
  name: consul
  datacenter: minikube

  tls:
    enabled: true
    enableAutoEncrypt: true

  acls:
    manageSystemACLs: true

  gossipEncryption:
    autoGenerate: true

  metrics:
    enabled: true
    enableAgentMetrics: true

server:
  replicas: 1

client:
  enabled: true

connectInject:
  enabled: true
  cni:
    enabled: true

ui:
  enabled: true

  metrics:
    enabled: true
    baseURL: "http://prometheus-kube-prometheus-prometheus.observability:9090"

  dashboardURLTemplates:
    service: "http://localhost:3000/d/adwqlwl/application-performance-monitoring?orgId=1&from=now-15m&to=now&timezone=browser&var-service={{Service.Name}}"