mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib

ports:
  prometheus:
    enabled: true
    containerPort: 8889
    servicePort: 8889
    protocol: TCP

serviceMonitor:
  enabled: true
  metricsEndpoints:
    - port: prometheus
      path: /metrics
      interval: 5s

config:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318

  exporters:
    prometheus:
      endpoint: 0.0.0.0:8889
      enable_open_metrics: true

    otlp_http/jaeger:
      endpoint: http://jaeger:4318
      tls:
        insecure: true

  processors:
    batch: { }

  service:
    pipelines:
      traces:
        receivers: [ otlp ]
        processors: [ batch ]
        exporters: [ otlp_http/jaeger ]

      metrics:
        receivers: [ otlp ]
        processors: [ batch ]
        exporters: [ prometheus ]