mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

config:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318

  processors:
    batch: { }

  exporters:
    otlp:
      endpoint: tempo.observability.svc.cluster.local:4318
      tls:
        insecure: true

  service:
    pipelines:
      traces:
        receivers: [ otlp ]
        processors: [ batch ]
        exporters: [ otlp ]