mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib

ports:
  prometheus:
    enabled: true
    containerPort: 8889
    servicePort: 8889
    protocol: TCP

serviceMonitor:
  enabled: true
  metricsEndpoints:
    - port: prometheus
      path: /metrics
      interval: 5s

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317

  exporters:
    otlp/jaeger:
      endpoint: http://jaeger:4317
      tls:
        insecure: true

    prometheus:
      endpoint: 0.0.0.0:8889
      enable_open_metrics: true
      resource_to_telemetry_conversion:
        enabled: true

    otlphttp/loki:
      endpoint: http://loki:3100/otlp

  processors:
    batch: { }

  connectors:
    spanmetrics:

  service:
    pipelines:
      traces:
        receivers: [ otlp ]
        processors: [ batch ]
        exporters: [ spanmetrics, otlp/jaeger ]

      metrics:
        receivers: [ otlp, spanmetrics ]
        processors: [ batch ]
        exporters: [ prometheus ]

      logs:
        receivers: [ otlp ]
        processors: [ batch ]
        exporters: [ otlphttp/loki ]