alertmanager:
  enabled: false

grafana:
  sidecar:
    datasources:
      exemplarTraceIdDestinations:
        datasourceUid: jaeger
        traceIdLabelName: trace_id
        urlDisplayLabel: View traces
  additionalDataSources:
    - name: Jaeger
      type: jaeger
      uid: jaeger
      access: proxy
      url: http://jaeger:16686
      jsonData:
        tracesToMetrics:
          datasourceUid: prometheus
          spanStartTimeShift: "-5m"
          spanEndTimeShift: "5m"
          tags:
            - key: service.name
              value: service

prometheus:
  prometheusSpec:
    retention: 6h
    scrapeInterval: 5s
    evaluationInterval: 30s

    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false

kubeScheduler:
  enabled: false

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false