alertmanager:
  enabled: false

grafana:
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL
    datasources:
      exemplarTraceIdDestinations:
        datasourceUid: jaeger
        traceIdLabelName: trace_id
        urlDisplayLabel: View traces

  additionalDataSources:
    - name: Jaeger
      type: jaeger
      uid: jaeger
      access: proxy
      url: http://jaeger:16686
      jsonData:
        tracesToMetrics:
          datasourceUid: prometheus
          spanStartTimeShift: "-5m"
          spanEndTimeShift: "5m"
          tags:
            - key: service.name
              value: service
        tracesToLogsV2:
          datasourceUid: loki
          spanStartTimeShift: "-5m"
          spanEndTimeShift: "5m"
          tags:
            - key: service.name
              value: service
          filterByTraceID: true
          filterBySpanID: false

    - name: Loki
      type: loki
      uid: loki
      access: proxy
      url: http://loki:3100
      jsonData:
        derivedFields:
          - name: TraceID
            matcherRegex: '"trace_id":"([a-f0-9]+)"'
            datasourceUid: jaeger
            url: "$${__value.raw}"

prometheus:
  prometheusSpec:
    retention: 6h
    scrapeInterval: 5s
    evaluationInterval: 30s

    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false

kubeScheduler:
  enabled: false

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false